version: '3'

services:
  frontend:
    environment:
      CONNECTIONSTRING=mongodb://mongo:27017/
    build: .
    depends_on:
      - 'database'
    ports:
      - '30003:3003'

  database:
    image: mongo:latest

########^^^ sdc_v2 ^^^############
########vvv fec_v1 vvv############

# version: '3'
# services:
#  checkout:
#   build:
#    context: .
#   ports:
#    - 3003:3003
#   environment:
#    - CONNECTIONSTRING=mongodb://mongo:27017/affordability
#   volumes:
#    - ./:/code
#  mongo:
#   image: mongo:4.4.3
#   ports:
#    - 27017:27017
#   volumes:
#    - mongodb:/data/db
#    - mongodb_config:/data/configdb
# volumes:
#   mongodb:
#   mongodb_config:

